apiVersion: v1
kind: Service
metadata:
  name: tetris-service
  labels:
    app: tetris-game
spec:
  type: NodePort
  selector:
    app: tetris-game
  ports:
    - name: http
      protocol: TCP
      port: 80          # Service port (cluster-internal)
      targetPort: 80    # Container port
      nodePort: 32000   # Node port exposed externally
